In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import load_iris

# Load sample data
data = load_iris()
X, y = data.data, data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an MLP classifier
mlp = MLPClassifier(hidden_layer_sizes=(100, ),        # Number of hidden layers and units per layer
                    activation='relu',                 # Activation function ('identity', 'logistic', 'tanh', 'relu')
                    solver='adam',                     # Solver for weight optimization ('lbfgs', 'sgd', 'adam')
                    alpha=0.0001,                      # L2 penalty (regularization term) parameter
                    batch_size='auto',                 # Size of minibatches for stochastic optimizers
                    learning_rate='constant',          # Learning rate schedule ('constant', 'invscaling', 'adaptive')
                    learning_rate_init=0.001,          # The initial learning rate
                    power_t=0.5,                       # The exponent for inverse scaling learning rate
                    max_iter=200,                      # Maximum number of iterations
                    shuffle=True,                      # Whether to shuffle samples in each iteration
                    random_state=None,                 # Seed for the random number generator
                    tol=0.0001,                        # Tolerance for the optimization
                    verbose=False,                     # Whether to print progress messages
                    warm_start=False,                  # Reuse the previous solution
                    momentum=0.9,                      # Momentum for gradient descent update
                    nesterovs_momentum=True,           # Whether to use Nesterov's momentum
                    early_stopping=False,              # Terminate training when validation score is not improving
                    validation_fraction=0.1,           # Proportion of training data to set aside as validation set
                    beta_1=0.9,                        # Exponential decay rate for estimates of first moment vector in adam
                    beta_2=0.999,                      # Exponential decay rate for estimates of second moment vector in adam
                    epsilon=1e-8,                      # Value for numerical stability in adam
                    n_iter_no_change=10,               # Maximum number of epochs without any improvement in the loss
                    max_fun=15000)                     # Maximum number of function calls for the solver

# Train the MLP classifier
mlp.fit(X_train, y_train)

# Make predictions
y_pred = mlp.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



C:\Users\tatas\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
